name: Sync

on:
  schedule:
    - cron: "0 10 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Sync
        env:
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          SRC_URI: ${{ secrets.SRC_URI }}
          DST_URI: ${{ secrets.DST_URI }}
        run: go run cmd/sync/sync.go
